#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Oct 16, 2021 02:09:06 PM JST  platform: Windows NT

import os
import threading

import tkinter as tk
from models.fileSelectBox import Path
from controller import Controller
from functools import partial

def vp_start_gui():
    root = tk.Tk()
    MainPanel (root)
    root.mainloop()

class MainPanel:
    def __init__(self, top: tk.Tk):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'

        # アプリ基本設定
        top.geometry("450x150+672+405")
        top.resizable(0,  0)
        top.title("MP4→PNG変換ツール")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")
        top.protocol("WM_DELETE_WINDOW", lambda: self.controller.shutDown(top))

        # タイトル
        self.Title = tk.Label(top)
        self.Title.place(relx=0.244, rely=0.0, height=41, width=234)
        self.Title.configure(activebackground="#f9f9f9")
        self.Title.configure(activeforeground="black")
        self.Title.configure(background="#d9d9d9")
        self.Title.configure(disabledforeground="#a3a3a3")
        self.Title.configure(font="-family {Yu Gothic UI} -size 18 -weight bold")
        self.Title.configure(foreground="#000000")
        self.Title.configure(highlightbackground="#d9d9d9")
        self.Title.configure(highlightcolor="black")
        self.Title.configure(text='''MP4→PNG変換ツール''')

        # MP4ファイルパスラベル
        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.08, rely=0.25, height=21, width=77)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''MP4ファイル''')

        # MP4ファイルパステキストボックス
        self.MP4Entry = tk.Entry(top)
        self.MP4Entry.place(relx=0.244, rely=0.25, height=20
                , relwidth=0.564)
        self.MP4Entry.configure(background="white")
        self.MP4Entry.configure(disabledforeground="#a3a3a3")
        self.MP4Entry.configure(font="TkFixedFont")
        self.MP4Entry.configure(foreground="#000000")
        self.MP4Entry.configure(highlightbackground="#d9d9d9")
        self.MP4Entry.configure(highlightcolor="black")
        self.MP4Entry.configure(insertbackground="black")
        self.MP4Entry.configure(selectbackground="blue")
        self.MP4Entry.configure(selectforeground="white")
        self.MP4Entry.configure(state="readonly")

        # MP4ファイルパス参照ボタン
        self.FileRefButton = tk.Button(top)
        self.FileRefButton.place(relx=0.822, rely=0.25, height=24, width=35)
        self.FileRefButton.configure(activebackground="#ececec")
        self.FileRefButton.configure(activeforeground="#000000")
        self.FileRefButton.configure(background="#d9d9d9")
        self.FileRefButton.configure(disabledforeground="#a3a3a3")
        self.FileRefButton.configure(foreground="#000000")
        self.FileRefButton.configure(highlightbackground="#d9d9d9")
        self.FileRefButton.configure(highlightcolor="black")
        self.FileRefButton.configure(pady="0")
        self.FileRefButton.configure(text='''参照''')
        self.FileRefButton.configure(command=lambda: self.controller.onClickFileRef(self.MP4Entry, [("MP4ファイル", "mp4")], self.getCurrentPath(self.MP4Entry.get())))

        # 出力先フォルダラベル
        self.Label2 = tk.Label(top)
        self.Label2.place(relx=0.01, rely=0.5, height=21, width=100)
        self.Label2.configure(background="#d9d9d9")
        self.Label2.configure(disabledforeground="#a3a3a3")
        self.Label2.configure(foreground="#000000")
        self.Label2.configure(text='''PNG出力先フォルダ''')

        # 出力先フォルダテキストボックス
        self.FolderPathEntry = tk.Entry(top)
        self.FolderPathEntry.place(relx=0.244, rely=0.5, height=20, relwidth=0.564)
        self.FolderPathEntry.configure(background="white")
        self.FolderPathEntry.configure(disabledforeground="#a3a3a3")
        self.FolderPathEntry.configure(font="TkFixedFont")
        self.FolderPathEntry.configure(foreground="#000000")
        self.FolderPathEntry.configure(insertbackground="black")
        self.FolderPathEntry.configure(state="readonly")

        # 出力先フォルダ参照ボタン
        self.FolderRefButton = tk.Button(top)
        self.FolderRefButton.place(relx=0.822, rely=0.5, height=24, width=35)
        self.FolderRefButton.configure(activebackground="#ececec")
        self.FolderRefButton.configure(activeforeground="#000000")
        self.FolderRefButton.configure(background="#d9d9d9")
        self.FolderRefButton.configure(disabledforeground="#a3a3a3")
        self.FolderRefButton.configure(foreground="#000000")
        self.FolderRefButton.configure(highlightbackground="#d9d9d9")
        self.FolderRefButton.configure(highlightcolor="black")
        self.FolderRefButton.configure(pady="0")
        self.FolderRefButton.configure(text='''参照''')
        self.FolderRefButton.configure(command=lambda: self.controller.onClickFolderRef(self.FolderPathEntry, self.getCurrentPath(self.FolderPathEntry.get())))

        # 変換ボタン
        self.ConvertButton = tk.Button(top)
        self.ConvertButton.place(relx=0.089, rely=0.75, height=24, width=367)
        self.ConvertButton.configure(activebackground="#ececec")
        self.ConvertButton.configure(activeforeground="#000000")
        self.ConvertButton.configure(background="#d9d9d9")
        self.ConvertButton.configure(disabledforeground="#a3a3a3")
        self.ConvertButton.configure(foreground="#000000")
        self.ConvertButton.configure(highlightbackground="#d9d9d9")
        self.ConvertButton.configure(highlightcolor="black")
        self.ConvertButton.configure(pady="0")
        self.ConvertButton.configure(text='''変換''')
        self.ConvertButton.configure(command=lambda: self.controller.onClickConvert())

        self.controller = Controller()

    def getCurrentPath(self, path: str) -> str:
        if path:
            return os.path.abspath(path)
        else:
            return os.path.abspath(os.path.dirname(__file__))

if __name__ == '__main__':
    vp_start_gui()





